### ISSUE TITLE
Short dump when there is bad cofile.

### ISSUE THREAD

**Issue by OgnianKalaydjiev** [ZEdwin/ZTCT#8]
First **tank you** for the greate tool. 
There is an dum when there exists issues with cofile in transport queue.
see dump.
![image](https://user-images.githubusercontent.com/74183943/98532328-38e07f00-228a-11eb-9fe2-f12761d42371.png)
I made quick  fix to suppress it . But i am not sure is this enough for the rest of your logic. 
```
 METHOD get_import_datetime_qas.
    DATA: ta_stms_wbo_requests TYPE TABLE OF stms_wbo_request,
          st_stms_wbo_requests TYPE stms_wbo_request.
    DATA: st_systems           TYPE ctslg_system.
*   Get the last date the object was imported
*->Tyr catch add on 'TR_READ_GLOBAL_INFO_OF_REQUEST' ->Begin
   TRY .
        CALL FUNCTION 'TR_READ_GLOBAL_INFO_OF_REQUEST'
          EXPORTING
            iv_trkorr = im_trkorr
          IMPORTING
            es_cofile = st_request-cofile.
     CATCH cx_root.
        RETURN.
    ENDTRY.
*->Tyr catch add on 'TR_READ_GLOBAL_INFO_OF_REQUEST' - END
```
Hope this helps.
Cheers Ogi

**Comment by OgnianKalaydjiev** [comment]
Probably error is misleading.
The issues is in first call  me->get_import_datetime_qas( EXPORTING im_trkorr  = ls_older_line-trkorr.
ls_older_line  is no initialise yet. I assume that you probably whant  me->get_import_datetime_qas( EXPORTING im_trkorr  = **ls_older_line-trkorr** to be  me->get_import_datetime_qas( EXPORTING im_trkorr  = **ls_newer_line-trkorr**
```
*           Fill conflict list
            MOVE-CORRESPONDING ls_newer_line TO me->conflict_line.
            me->conflict_line-warning_lvl  = co_error.
            me->conflict_line-warning_rank = co_error_rank.
            me->conflict_line-warning_txt  = lp_error_text.
            me->conflict_line-objkey       = tp_tabkey.
*           Get the last date the object was imported
            me->get_import_datetime_qas( EXPORTING im_trkorr  = ls_older_line-trkorr
                                         IMPORTING ex_as4time = me->conflict_line-as4time
                                                   ex_as4date = me->conflict_line-as4date ).
```
Cheers Ogi

**Comment by ZEdwin** [comment]
Thanks! Very late response from my side, but well spotted. I have corrected this.
